In [2]:
import numpy as np
height = np.round(np.random.normal(1.75, 0.20, 5000), 2)
weight = np.round(np.random.normal(60.32, 15, 5000), 2)
np_city = np.column_stack((height, weight))
np_city

array([[  1.83,  47.3 ],
       [  1.69,  79.96],
       [  1.9 ,  51.85],
       ..., 
       [  1.65,  98.08],
       [  1.75,  55.92],
       [  1.82,  35.98]])

In [13]:
x = np.array([7, 7, 5, 4, 5, 5, 5, 7])
y = np.array([8, 0, 6, 1, 6, 3, 4, 2])
cols = np.column_stack((x,y))
cols

array([[7, 8],
       [7, 0],
       [5, 6],
       [4, 1],
       [5, 6],
       [5, 3],
       [5, 4],
       [7, 2]])

In [46]:
import numpy as np
x = [3, 6, 11]
y = [9, 20, 17]
z = [5,8,20]
np_2d = np.array([x, y])
# print(np_2d)
np_cols = np.column_stack((x,y,z))
print(np_cols)
print np_cols[1,:2]
print np_cols[1:2,:2]

[[ 3  9  5]
 [ 6 20  8]
 [11 17 20]]
[ 6 20]
[[ 6 20]]


In [16]:
import numpy as np
store = [1, 2, 3, 4, 5, 6]
cost = [94, 87, 81, 96, 97, 92]
np_cols = np.column_stack((store, cost))
np_rows = np.array([store,cost])
print(np_cols)
print(np_rows)

[[ 1 94]
 [ 2 87]
 [ 3 81]
 [ 4 96]
 [ 5 97]
 [ 6 92]]
[[ 1  2  3  4  5  6]
 [94 87 81 96 97 92]]


In [22]:
z = [x,y]
z

[[3, 6, 11], [9, 20, 17]]

In [43]:
z[:1][0][2]

11

In [50]:
points = np.arange(-5,5,1)
xs,ys = np.meshgrid(points,points)
print xs
print ys

[[-5 -4 -3 -2 -1  0  1  2  3  4]
 [-5 -4 -3 -2 -1  0  1  2  3  4]
 [-5 -4 -3 -2 -1  0  1  2  3  4]
 [-5 -4 -3 -2 -1  0  1  2  3  4]
 [-5 -4 -3 -2 -1  0  1  2  3  4]
 [-5 -4 -3 -2 -1  0  1  2  3  4]
 [-5 -4 -3 -2 -1  0  1  2  3  4]
 [-5 -4 -3 -2 -1  0  1  2  3  4]
 [-5 -4 -3 -2 -1  0  1  2  3  4]
 [-5 -4 -3 -2 -1  0  1  2  3  4]]
[[-5 -5 -5 -5 -5 -5 -5 -5 -5 -5]
 [-4 -4 -4 -4 -4 -4 -4 -4 -4 -4]
 [-3 -3 -3 -3 -3 -3 -3 -3 -3 -3]
 [-2 -2 -2 -2 -2 -2 -2 -2 -2 -2]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 1  1  1  1  1  1  1  1  1  1]
 [ 2  2  2  2  2  2  2  2  2  2]
 [ 3  3  3  3  3  3  3  3  3  3]
 [ 4  4  4  4  4  4  4  4  4  4]]


In [55]:
arr = np.random.randn(5,4)
print arr
arr.sum(1)

[[ 1.20953485 -2.16533631 -1.52436574 -1.61915239]
 [-0.66445606  0.03924831  0.09892668  0.21937996]
 [ 0.27515232 -2.17822032 -0.11632626 -1.40534934]
 [-0.93871459  0.86213491 -1.14426009  0.39380504]
 [ 0.12713805  1.35296188 -1.19484839 -0.22641163]]


array([-4.09931959, -0.30690112, -3.4247436 , -0.82703473,  0.05883991])

In [59]:
np.random.randint(0,2,size=10)

array([0, 0, 0, 1, 1, 0, 0, 0, 1, 0])

In [74]:
import pandas as pd
df = pd.DataFrame(arr)
df.columns = ['a', 'b', 'c', 'd']
df.index = ['Jan', 'Feb', 'Mar', 'Apr', 'May']
df['Jan': 'Apr']
df.loc[:,'a':'c']

<div>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>a</th>
      <th>b</th>
      <th>c</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>Jan</th>
      <td>1.209535</td>
      <td>-2.165336</td>
      <td>-1.524366</td>
    </tr>
    <tr>
      <th>Feb</th>
      <td>-0.664456</td>
      <td>0.039248</td>
      <td>0.098927</td>
    </tr>
    <tr>
      <th>Mar</th>
      <td>0.275152</td>
      <td>-2.178220</td>
      <td>-0.116326</td>
    </tr>
    <tr>
      <th>Apr</th>
      <td>-0.938715</td>
      <td>0.862135</td>
      <td>-1.144260</td>
    </tr>
    <tr>
      <th>May</th>
      <td>0.127138</td>
      <td>1.352962</td>
      <td>-1.194848</td>
    </tr>
  </tbody>
</table>
</div>

In [101]:
df1 = pd.DataFrame(np.random.randn(6,4),index=list('abcdef'), columns=list('ABCD'))
df1.loc[['a', 'b', 'd']]
# df1.loc['a':'b']

<div>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>A</th>
      <th>B</th>
      <th>C</th>
      <th>D</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>a</th>
      <td>0.824961</td>
      <td>-0.863939</td>
      <td>0.563155</td>
      <td>-0.036780</td>
    </tr>
    <tr>
      <th>b</th>
      <td>0.700796</td>
      <td>0.384699</td>
      <td>-1.307045</td>
      <td>-0.145695</td>
    </tr>
    <tr>
      <th>d</th>
      <td>-0.075030</td>
      <td>1.482830</td>
      <td>-0.719811</td>
      <td>0.271505</td>
    </tr>
  </tbody>
</table>
</div>

In [85]:
arrays = [np.array(['bar', 'bar', 'baz', 'baz', 'foo', 'foo', 'qux', 'qux']),
          np.array(['one', 'two', 'one', 'two', 'one', 'two', 'one', 'two'])]
df = pd.DataFrame(np.random.randn(8, 4), index=arrays)
df.loc[(['bar','qux'], 'one'),:]
# df.loc[(['bar','qux'], 'one')]

<div>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th></th>
      <th>0</th>
      <th>1</th>
      <th>2</th>
      <th>3</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th rowspan="2" valign="top">bar</th>
      <th>one</th>
      <td>-0.807797</td>
      <td>-0.957671</td>
      <td>2.324870</td>
      <td>-0.990436</td>
    </tr>
    <tr>
      <th>two</th>
      <td>-0.873134</td>
      <td>-0.036077</td>
      <td>0.183158</td>
      <td>2.297430</td>
    </tr>
    <tr>
      <th rowspan="2" valign="top">baz</th>
      <th>one</th>
      <td>0.271280</td>
      <td>0.185403</td>
      <td>-1.052771</td>
      <td>0.908068</td>
    </tr>
    <tr>
      <th>two</th>
      <td>-0.153225</td>
      <td>0.690233</td>
      <td>-0.879029</td>
      <td>-0.412407</td>
    </tr>
    <tr>
      <th rowspan="2" valign="top">foo</th>
      <th>one</th>
      <td>0.561014</td>
      <td>1.791097</td>
      <td>-0.101980</td>
      <td>0.205601</td>
    </tr>
    <tr>
      <th>two</th>
      <td>-0.202219</td>
      <td>1.263018</td>
      <td>-0.698919</td>
      <td>0.633629</td>
    </tr>
    <tr>
      <th rowspan="2" valign="top">qux</th>
      <th>one</th>
      <td>0.606539</td>
      <td>-1.110295</td>
      <td>-0.027826</td>
      <td>0.243018</td>
    </tr>
    <tr>
      <th>two</th>
      <td>1.233994</td>
      <td>-0.835786</td>
      <td>2.245231</td>
      <td>-1.068872</td>
    </tr>
  </tbody>
</table>
</div>

In [99]:
df.loc[(['bar','qux'], 'one'),:]

<div>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th></th>
      <th>0</th>
      <th>1</th>
      <th>2</th>
      <th>3</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>bar</th>
      <th>one</th>
      <td>-0.807797</td>
      <td>-0.957671</td>
      <td>2.324870</td>
      <td>-0.990436</td>
    </tr>
    <tr>
      <th>qux</th>
      <th>one</th>
      <td>0.606539</td>
      <td>-1.110295</td>
      <td>-0.027826</td>
      <td>0.243018</td>
    </tr>
  </tbody>
</table>
</div>

In [112]:
x = np.arange(6)
x, x[::-13]

(array([0, 1, 2, 3, 4, 5]), array([5]))