In [24]:
import numpy as np
import scipy.linalg as lg 

# use np.array to express a Matrix
A = np.array([[1,0],[1,1],[1,2]])
# use 2D array to express a Vector and don't use 1D array to express a vector
# b = np.array([5,6]) #1D array
b = np.array([[6,0,0]])

In [17]:
# not matrix production
A*b.T

array([[6, 0],
       [0, 0],
       [0, 0]])

In [8]:
# get first column of A
A[:,0]

array([1, 1, 1])

In [7]:
A.shape

(3, 2)

In [16]:
#matrix multiplication
A.T.dot(b.T)

array([[6],
       [0]])

In [15]:
b.T

array([[6],
       [0],
       [0]])

In [11]:
A.T

array([[1, 1, 1],
       [0, 1, 2]])

In [26]:
Q, R = lg.qr(A,mode='r')
Q

ValueError: need more than 1 value to unpack

In [37]:
x = Q.T.dot(b.T)
x

array([[-3.46410162],
       [ 4.24264069]])

In [39]:
x = linalg.inv(R).dot(Q.T).dot(b.T)
x

array([[ 5.],
       [-3.]])

In [1]:
import matplotlib.pyplot as plt

In [2]:
import mpl_toolkits.mplot3d

In [4]:
print "daf"

daf
